name: power
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5 # Or latest version
  fl_chart: ^0.70.2
  http: ^1.1.0    # Or latest version
  firebase_core: ^2.24.2 # Or latest version
  firebase_database: ^10.3.8 # Or latest version
  shared_preferences: ^2.2.2 # Or latest version
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true



